---
:concurrency: 2
staging:
  :concurrency: 2
production:
  :concurrency: 2
# :pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - [viber, 1]
  - [whatsapp, 2]
  - [telegram, 3]
# :daemon: true
