---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - [viber, 1]
  - [whatsapp, 2]
  - [telegram, 3]
# :daemon: true
